openapi: 3.0.3
info:
  title: Graph Reconnection Service
  description: |-
    This is a sample Reconnection Service endpoint profile based on the OpenAPI 3.0 specification.
  version: 1.0.0
servers:
  - url: https://localhost/api/v1.0.0
tags:
  - name: connections
    description: Social graph connections webhook
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /connections/{dsnpId}:
    get:
      tags:
        - connections
      summary: Get social connections for a user by their DSNPId
      description: Returns social connections for a user
      operationId: getConnectionsByDSNPId
      parameters:
        - name: dsnpId
          in: path
          description: DSNPId of the user's social connections to return
          required: true
          schema:
            type: integer
            format: int64  # Represents a 64-bit integer
            minimum: 1     # Ensures the integer is non-negative
            maximum: 18446744073709551615  # Maximum value of a u64
        - name: pagination
          in: query
          description: Pagination parameters
          required: false
          schema:
            type: object
            properties:
              pageNumber:
                type: integer
                minimum: 1
              pageSize:
                type: integer
                minimum: 1
                maximum: 100
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionsApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConnectionsApiResponse'
        '400':
          description: Invalid DSNPId supplied
        '404':
          description: DSNPId not found
      security:
        - api_key: []
        - connections_auth:
            - read:connections
  /health:
    get:
      tags:
        - health
      summary: Check if the provider webhook is alive
      operationId: healthCheck
      responses:
        '200':
          description: Provider webhook is alive
      security: []  # No security required for health check
components:
  schemas:
    ConnectionsApiResponse:
      type: object
      properties:
        dsnpId:
          type: integer
          format: int64
          example: 10
        connections:
          $ref: '#/components/schemas/Connections'
        graphKeyPairs:
          $ref: '#/components/schemas/GraphKeyPairs'
    Connections:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
        pagination:
          type: object
          properties:
            pageNumber:
              type: integer
            pageSize:
              type: integer
            pageCount:
              type: integer
      xml:
        name: connections
      example:
        data:
          - dsnpId: 1024
            privacyType: "Public"
            direction: "connectionTo"
            connectionType: "Follow"
          - dsnpId: 2048
            privacyType: "Private"
            direction: "bidirectional"
            connectionType: "Friendship"
          - dsnpId: 3072
            privacyType: "Public"
            direction: "connectionFrom"
            connectionType: "Follow"
        pagination:
          pageNumber: 1
          pageSize: 10
          pageCount: 100
    Connection:
      type: object
      properties:
        dsnpId:
          type: integer
          format: int64
        privacyType:
          type: string
          enum:
            - Public
            - Private
        direction:
          type: string
          enum:
            - connectionTo
            - bidirectional
            - connectionFrom
        connectionType:
          type: string
          enum:
            - Follow
            - Friendship
    GraphKeyPairs:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/GraphKeyPair'
    GraphKeyPair:
      type: object
      properties:
        keyType:
          type: string
          example: "X25519"
        publicKey:
          type: string
          example: "0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a"
        privateKey:
          type: string
          example: "0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d"
      xml:
        name: graph key pair
  securitySchemes:
    connections_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://localhost/oauth/authorize
          scopes:
            read:connections: read a user's connections
    api_key:
      type: apiKey
      name: api_key
      in: header
