version: '3'

services:
  reconnection-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.docker.dev
    ports:
      - 6379:6379
    volumes:
    - .:/app
    networks:
      - reconnection-service-network-dev

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - reconnection-service-network-dev
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  reconnection-service-network-dev:
