version: '3'

services:
  reconnection-service:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.docker.dev
    volumes:
    - ./:/app
    networks:
      - reconnection-service-network-dev

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - reconnection-service-network-dev
    volumes:
      - redis_data:/data

  frequency:
    image: frequencychain/instant-seal-node:latest
    ports:
      - 9944:9944
    networks:
      - reconnection-service-network-dev
    container_name: frequency-node

  webhook:
    container_name: webhook
    build:
      context: .
      dockerfile: webhook-specification/mock-webhook-server/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./webhook-specification/mock-webhook-server:/app
    networks:
      - reconnection-service-network-dev

volumes:
  redis_data:

networks:
  reconnection-service-network-dev:
